

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Optional
from uuid import UUID, uuid4


# ─────────────────────────────────────────────────────────────────────────────
# Source Classification
# ─────────────────────────────────────────────────────────────────────────────

class ContentType(str, Enum):
    EMAIL = "email"
    MEETING_NOTES = "meeting_notes"
    CALENDAR_EVENT = "calendar_event"
    INSTANT_MESSAGE = "instant_message"
    DOCUMENT = "document"
    SPREADSHEET = "spreadsheet"
    PRESENTATION = "presentation"
    NOTE = "note"
    TASK = "task"
    COMMENT = "comment"
    VOICE_TRANSCRIPT = "voice_transcript"
    UNKNOWN = "unknown"


class ConnectorSource(str, Enum):
    OUTLOOK = "outlook"
    GMAIL = "gmail"
    TEAMS = "teams"
    SLACK = "slack"
    NOTION = "notion"
    GOOGLE_DRIVE = "google_drive"
    LOCAL_UPLOAD = "local_upload"
    SHAREPOINT = "sharepoint"
    WHATSAPP = "whatsapp"        # Future
    ZOOM = "zoom"                # Future


class ProcessingStatus(str, Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    EMBEDDED = "embedded"
    FAILED = "failed"
    SKIPPED = "skipped"


# ─────────────────────────────────────────────────────────────────────────────
# Participant
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Participant:
    """A person involved in a piece of content."""
    email: Optional[str] = None
    display_name: Optional[str] = None
    role: str = "participant"                    # "sender", "recipient", "cc", "attendee"
    person_id: Optional[UUID] = None             # Resolved entity ID (populated after entity matching)
    company_id: Optional[UUID] = None            # Resolved company


# ─────────────────────────────────────────────────────────────────────────────
# Attachment Reference
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class AttachmentRef:
    """Reference to a file attached to a piece of content."""
    filename: str
    mime_type: Optional[str] = None
    size_bytes: Optional[int] = None
    storage_path: Optional[str] = None          # MinIO path after upload
    is_processed: bool = False


# ─────────────────────────────────────────────────────────────────────────────
# Extracted Signals
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class ExtractedSignal:
    """
    A signal extracted from content by the NLP pipeline.
    Signals become commitments, risks, or decisions in the entity layer.
    """
    signal_type: str                             # "commitment", "risk", "decision", "action_item"
    text: str                                    # The extracted text
    confidence: float                            # 0.0–1.0
    owner_email: Optional[str] = None
    deadline_text: Optional[str] = None         # Raw text, e.g., "by Friday"
    deadline_parsed: Optional[datetime] = None  # Parsed datetime if resolvable


# ─────────────────────────────────────────────────────────────────────────────
# CANONICAL DOCUMENT — The Universal Internal Format
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class CanonicalDocument:
    """
    The single internal representation for all ingested content.

    Every connector produces this format.
    Every pipeline stage consumes this format.
    The LLM never sees the raw source format.

    Sources → CanonicalDocument → Entity Extraction → Storage → Embedding

    Field conventions:
      - id: system-generated UUID
      - source_id: original ID from the external system
      - content_type: what kind of content this is
      - connector_source: where it came from
      - occurred_at: when it happened (not when it was ingested)
      - ingested_at: when the system received it
      - title: human-readable title or subject
      - body_text: full text content (cleaned)
      - body_summary: short summary (generated by pipeline)
      - participants: all people involved
      - attachments: any files referenced
      - extracted_signals: NLP-detected commitments/risks/decisions
      - entity_ids: resolved entity IDs after matching
      - meta: flexible bag for source-specific metadata
    """

    # System identity
    id: UUID = field(default_factory=uuid4)
    ingested_at: datetime = field(default_factory=datetime.utcnow)

    # Source identity
    source_id: str = ""                          # External system's ID
    connector_source: ConnectorSource = ConnectorSource.LOCAL_UPLOAD
    content_type: ContentType = ContentType.UNKNOWN
    source_url: Optional[str] = None             # Link back to original

    # Content
    title: Optional[str] = None                 # Subject line, filename, meeting title
    body_text: str = ""                          # Full cleaned text
    body_summary: Optional[str] = None           # Short summary (max 500 chars)
    language: str = "en"

    # Timing
    occurred_at: Optional[datetime] = None      # When this happened in the real world
    thread_id: Optional[str] = None             # Email thread, Slack thread, etc.

    # Participants
    participants: list[Participant] = field(default_factory=list)

    # Attachments
    attachments: list[AttachmentRef] = field(default_factory=list)

    # Extracted Intelligence
    extracted_signals: list[ExtractedSignal] = field(default_factory=list)

    # Resolved Entity Links (populated after entity matching)
    person_ids: list[UUID] = field(default_factory=list)
    company_ids: list[UUID] = field(default_factory=list)
    project_ids: list[UUID] = field(default_factory=list)

    # Processing State
    processing_status: ProcessingStatus = ProcessingStatus.PENDING
    embedding_ids: list[str] = field(default_factory=list)   # Qdrant point IDs
    chunk_count: int = 0
    processing_error: Optional[str] = None

    # Deduplication
    content_hash: Optional[str] = None          # SHA-256 of body_text

    # Flexible metadata (source-specific fields that don't fit the schema)
    meta: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if self.body_text and not self.content_hash:
            self.content_hash = hashlib.sha256(
                self.body_text.encode("utf-8")
            ).hexdigest()

    @property
    def sender(self) -> Optional[Participant]:
        for p in self.participants:
            if p.role == "sender":
                return p
        return self.participants[0] if self.participants else None

    @property
    def recipients(self) -> list[Participant]:
        return [p for p in self.participants if p.role in ("recipient", "cc", "to")]

    @property
    def attendees(self) -> list[Participant]:
        return [p for p in self.participants if p.role == "attendee"]

    @property
    def commitment_signals(self) -> list[ExtractedSignal]:
        return [s for s in self.extracted_signals if s.signal_type == "commitment"]

    @property
    def risk_signals(self) -> list[ExtractedSignal]:
        return [s for s in self.extracted_signals if s.signal_type == "risk"]

    def to_chunk_payload(self, chunk_text: str, chunk_index: int) -> dict[str, Any]:
        """
        Serialize chunk metadata for Qdrant vector storage.
        This is the payload stored alongside each embedding.
        """
        return {
            "document_id": str(self.id),
            "source_id": self.source_id,
            "source_type": self.connector_source.value,
            "content_type": self.content_type.value,
            "title": self.title,
            "text": chunk_text,
            "chunk_index": chunk_index,
            "occurred_at": self.occurred_at.isoformat() if self.occurred_at else None,
            "person_ids": [str(pid) for pid in self.person_ids],
            "company_ids": [str(cid) for cid in self.company_ids],
            "project_ids": [str(pid) for pid in self.project_ids],
            "thread_id": self.thread_id,
        }

    def to_db_dict(self) -> dict[str, Any]:
        """Serialize to a flat dict for database storage."""
        return {
            "id": self.id,
            "source_id": self.source_id,
            "source_type": self.connector_source.value,
            "content_type": self.content_type.value,
            "title": self.title,
            "source_url": self.source_url,
            "occurred_at": self.occurred_at,
            "ingested_at": self.ingested_at,
            "body_summary": self.body_summary,
            "chunk_count": self.chunk_count,
            "processing_status": self.processing_status.value,
            "content_hash": self.content_hash,
            "meta": self.meta,
        }


# ─────────────────────────────────────────────────────────────────────────────
# Normalizers — Source-Specific → CanonicalDocument
# ─────────────────────────────────────────────────────────────────────────────

class OutlookNormalizer:
    """Converts raw Outlook Graph API email payload → CanonicalDocument."""

    def normalize(self, raw: dict[str, Any]) -> CanonicalDocument:
        participants = []

        sender = raw.get("from", {}).get("emailAddress", {})
        if sender:
            participants.append(Participant(
                email=sender.get("address"),
                display_name=sender.get("name"),
                role="sender",
            ))

        for recipient in raw.get("toRecipients", []):
            addr = recipient.get("emailAddress", {})
            participants.append(Participant(
                email=addr.get("address"),
                display_name=addr.get("name"),
                role="recipient",
            ))

        for cc in raw.get("ccRecipients", []):
            addr = cc.get("emailAddress", {})
            participants.append(Participant(
                email=addr.get("address"),
                display_name=addr.get("name"),
                role="cc",
            ))

        body = raw.get("body", {}).get("content", "")

        return CanonicalDocument(
            source_id=raw.get("id", ""),
            connector_source=ConnectorSource.OUTLOOK,
            content_type=ContentType.EMAIL,
            source_url=raw.get("webLink"),
            title=raw.get("subject"),
            body_text=self._clean_html(body),
            occurred_at=self._parse_date(raw.get("sentDateTime")),
            thread_id=raw.get("conversationId"),
            participants=participants,
            meta={
                "importance": raw.get("importance"),
                "has_attachments": raw.get("hasAttachments", False),
                "internet_message_id": raw.get("internetMessageId"),
            },
        )

    def _clean_html(self, html: str) -> str:
        import re
        clean = re.sub(r"<[^>]+>", " ", html)
        clean = re.sub(r"\s+", " ", clean).strip()
        return clean

    def _parse_date(self, date_str: Optional[str]) -> Optional[datetime]:
        if not date_str:
            return None
        from dateutil import parser
        try:
            return parser.parse(date_str)
        except Exception:
            return None


class SlackNormalizer:
    """Converts raw Slack message payload → CanonicalDocument."""

    def normalize(self, raw: dict[str, Any], channel_name: str = "") -> CanonicalDocument:
        participants = [
            Participant(
                email=None,
                display_name=raw.get("user", ""),
                role="sender",
            )
        ]

        ts = raw.get("ts", "")
        occurred_at = None
        if ts:
            try:
                occurred_at = datetime.fromtimestamp(float(ts))
            except Exception:
                pass

        return CanonicalDocument(
            source_id=ts,
            connector_source=ConnectorSource.SLACK,
            content_type=ContentType.INSTANT_MESSAGE,
            title=f"Slack: #{channel_name}",
            body_text=raw.get("text", ""),
            occurred_at=occurred_at,
            thread_id=raw.get("thread_ts"),
            participants=participants,
            meta={
                "channel": channel_name,
                "channel_id": raw.get("channel"),
                "reaction_count": len(raw.get("reactions", [])),
            },
        )


class NotionNormalizer:
    """Converts Notion page payload → CanonicalDocument."""

    def normalize(self, raw: dict[str, Any], blocks: list[dict]) -> CanonicalDocument:
        title = ""
        props = raw.get("properties", {})
        for prop_name, prop_val in props.items():
            if prop_val.get("type") == "title":
                texts = prop_val.get("title", [])
                title = "".join(t.get("plain_text", "") for t in texts)
                break

        body_lines = []
        for block in blocks:
            block_type = block.get("type", "")
            block_content = block.get(block_type, {})
            rich_text = block_content.get("rich_text", [])
            text = "".join(t.get("plain_text", "") for t in rich_text)
            if text.strip():
                body_lines.append(text)

        created_time = raw.get("created_time")
        occurred_at = None
        if created_time:
            from dateutil import parser
            try:
                occurred_at = parser.parse(created_time)
            except Exception:
                pass

        return CanonicalDocument(
            source_id=raw.get("id", ""),
            connector_source=ConnectorSource.NOTION,
            content_type=ContentType.NOTE,
            source_url=raw.get("url"),
            title=title,
            body_text="\n".join(body_lines),
            occurred_at=occurred_at,
            meta={
                "page_id": raw.get("id"),
                "last_edited": raw.get("last_edited_time"),
                "created_by": raw.get("created_by", {}).get("id"),
            },
        )


class TeamsNormalizer:
    """Converts Microsoft Teams message payload → CanonicalDocument."""

    def normalize(self, raw: dict[str, Any]) -> CanonicalDocument:
        sender_info = raw.get("from", {}).get("user", {})
        participants = [
            Participant(
                email=None,
                display_name=sender_info.get("displayName", ""),
                role="sender",
            )
        ]

        body = raw.get("body", {}).get("content", "")
        if raw.get("body", {}).get("contentType") == "html":
            import re
            body = re.sub(r"<[^>]+>", " ", body)
            body = re.sub(r"\s+", " ", body).strip()

        from dateutil import parser
        occurred_at = None
        created_at = raw.get("createdDateTime")
        if created_at:
            try:
                occurred_at = parser.parse(created_at)
            except Exception:
                pass

        return CanonicalDocument(
            source_id=raw.get("id", ""),
            connector_source=ConnectorSource.TEAMS,
            content_type=ContentType.INSTANT_MESSAGE,
            title=raw.get("subject") or "Teams Message",
            body_text=body,
            occurred_at=occurred_at,
            thread_id=raw.get("replyToId"),
            participants=participants,
            meta={
                "channel_identity": raw.get("channelIdentity"),
                "message_type": raw.get("messageType"),
                "importance": raw.get("importance"),
            },
        )


class LocalFileNormalizer:
    """Converts local file upload metadata + extracted text → CanonicalDocument."""

    def normalize(
        self,
        filename: str,
        extracted_text: str,
        mime_type: str,
        storage_path: str,
        file_size: int,
    ) -> CanonicalDocument:
        content_type = self._infer_content_type(mime_type, filename)

        return CanonicalDocument(
            source_id=storage_path,
            connector_source=ConnectorSource.LOCAL_UPLOAD,
            content_type=content_type,
            title=filename,
            body_text=extracted_text,
            occurred_at=datetime.utcnow(),
            attachments=[
                AttachmentRef(
                    filename=filename,
                    mime_type=mime_type,
                    size_bytes=file_size,
                    storage_path=storage_path,
                    is_processed=True,
                )
            ],
            meta={
                "mime_type": mime_type,
                "storage_path": storage_path,
                "file_size": file_size,
            },
        )

    def _infer_content_type(self, mime_type: str, filename: str) -> ContentType:
        ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
        mapping = {
            "pdf": ContentType.DOCUMENT,
            "docx": ContentType.DOCUMENT,
            "doc": ContentType.DOCUMENT,
            "xlsx": ContentType.SPREADSHEET,
            "xls": ContentType.SPREADSHEET,
            "pptx": ContentType.PRESENTATION,
            "ppt": ContentType.PRESENTATION,
            "txt": ContentType.NOTE,
            "md": ContentType.NOTE,
        }
        return mapping.get(ext, ContentType.DOCUMENT)
